apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  AUTH_SVC_ADDRESS: "auth:5000"
  AUTH_REQUEST_TIMEOUT: "5"
  MAX_UPLOAD_BYTES: "104857600"
  RABBITMQ_HOST: "rabbitmq"
  VIDEO_QUEUE: "video"
