apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
stringData:
  MONGO_VIDEO_URI: "mongodb://CHANGE_ME_USER:CHANGE_ME_PASSWORD@mongodb.example:27017/videos?authSource=admin"
  MONGO_MP3_URI: "mongodb://CHANGE_ME_USER:CHANGE_ME_PASSWORD@mongodb.example:27017/mp3s?authSource=admin"
type: Opaque
