apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData: 
  GMAIL_ADDRESS: "NONE" # email address to recieve the notification
  GMAIL_PASSWORD: "NONE" # password of email
type: Opaque
